/**
 *  NB Power Solar Billing Tracker  v1.5
 *
 *  Monitors energy data to compare the current NB Power net metering rate
 *  structure against the proposed three-part rate (import rate + export credit
 *  + demand charge), pending EUB approval April 1, 2027.
 *
 *  Both meter sources run simultaneously and independently:
 *
 *  SOURCE A — PowerMeter (watts), e.g. Emporia Vue via amithalp/EmporiaV2
 *    - Two devices: "mains from grid" and "mains to grid", both PowerMeter
 *    - App polls watts every minute and integrates to kWh internally
 *    - Feeds the 15-min rolling average for peak demand tracking
 *    - Optional — leave devices unset to disable Source A
 *
 *  SOURCE B — EnergyMeter (kWh, never-resetting), e.g. Aeotec
 *    - Grid consumption: total kWh drawn from NB Power (never resets)
 *    - Solar production: total kWh generated by inverter (never resets)
 *    - App snapshots both counters at billing period start, computes delta
 *    - Peak demand uses an optional PowerMeter, or estimates from kWh delta
 *    - Optional — leave devices unset to disable Source B
 *
 *  When both sources are active the app:
 *    - Calculates billing costs independently for each source
 *    - Compares import kWh, export kWh, and both cost models between sources
 *    - Flags discrepancies above a configurable threshold
 *    - Reports both sets of figures in the status paragraph and dashboard
 *    - Uses Source A peak demand for both billing calculations when available
 *      (watts integration is more accurate than kWh-delta estimation)
 *
 *  Billing formulas (applied to each source independently):
 *    Current net metering : (importKwh − exportKwh) × currentRate
 *    Proposed structure   : (importKwh × importRate)
 *                         − (exportKwh × exportRate)
 *                         + (peakKw    × demandCharge)
 *
 *  v1.5 changes:
 *    - Removed device mode selector — both sources now run simultaneously
 *    - All Source A and Source B devices are independently optional
 *    - Parallel billing calculations with cross-source discrepancy analysis
 *    - Status paragraph shows both sources side by side
 *    - Dashboard attributes expanded with A/B prefixed variants
 *    - Discrepancy alert notification when sources diverge beyond threshold
 *    - Peak demand from Source A (watts) shared with Source B calculations
 *      when available, for best accuracy
 *
 *  v1.4 changes:
 *    - Added Refresh Display button to manually update the status paragraph.
 *    - Corrected device brand name to Aeotec (was Anotech).
 *    - Clarified MODE B solar input is inverter total production, not export.
 *
 *  v1.3 changes:
 *    - Added MODE B: EnergyMeter (never-resetting kWh) device support.
 *    - Demand window (7 am–10 pm) enforced in both modes.
 *
 *  v1.2 changes:
 *    - Added importUrl to definition block for one-click Hubitat import.
 *
 *  v1.1 changes:
 *    - All device inputs use capability.powerMeter (watts) only.
 *    - Removed snapshot/manual accumulation mode choice.
 *
 *  Author : generated for Sébastien with Claude (Anthropic), May 2026
 *  License: Apache 2.0
 */

definition(
    name:        "NB Power Solar Billing Tracker",
    namespace:   "nbpower",
    author:      "Sébastien",
    description: "Tracks solar import/export kWh and 15-min peak demand from two " +
                 "independent meter sources (Emporia watts + Aeotec kWh) simultaneously, " +
                 "comparing current NB Power net metering against the proposed rate structure.",
    category:    "Energy Management",
    iconUrl:     "",
    iconX2Url:   "",
    importUrl:   "https://raw.githubusercontent.com/SebastienViel/NB-Power-Rates/main/NBPowerSolarBillingTracker%20for%20Hubitat.groovy"
)

// ---------------------------------------------------------------------------
// Preferences / UI
// ---------------------------------------------------------------------------
preferences {
    page(name: "mainPage")
    page(name: "sourceAPage")
    page(name: "sourceBPage")
    page(name: "ratesPage")
    page(name: "notificationsPage")
}

def mainPage() {
    dynamicPage(name: "mainPage", title: "NB Power Solar Billing Tracker", install: true, uninstall: true) {

        section("<b>Meter Sources</b>") {
            paragraph "Configure one or both sources. When both are active, readings are " +
                      "compared and discrepancies reported."
            href "sourceAPage",       title: "⚡ Source A — PowerMeter / watts (Emporia Vue)",
                                      description: sourceADescription(), required: false
            href "sourceBPage",       title: "🔋 Source B — EnergyMeter / kWh (Aeotec)",
                                      description: sourceBDescription(), required: false
            href "ratesPage",         title: "💲 Rate Settings",         description: ratesDescription(),  required: true
            href "notificationsPage", title: "🔔 Notifications",         description: notifyDescription()
        }

        section("<b>Billing Period</b>") {
            input "billingDay", "number",
                title: "Billing cycle start day of month (e.g. 1 for the 1st)",
                defaultValue: 1, range: "1..28", required: true
            paragraph "Current billing period: <b>${currentBillingPeriodLabel()}</b>"
        }

        section("<b>Dashboard Summary</b>") {
            input "summaryDevice", "capability.actuator",
                title: "Optional: Virtual device to write summary tile attributes to",
                required: false, multiple: false
            paragraph "Source A attributes: <i>nbpA_ImportKwh, nbpA_ExportKwh, nbpA_PeakKw, " +
                      "nbpA_CurrentCost, nbpA_ProposedCost, nbpA_Delta</i><br>" +
                      "Source B attributes: <i>nbpB_ImportKwh, nbpB_ExportKwh, " +
                      "nbpB_CurrentCost, nbpB_ProposedCost, nbpB_Delta</i><br>" +
                      "Shared: <i>nbpPeakKw, nbpPeakKwTime, nbpBillingStart, nbpDiscrepancy</i>"
        }

        section("<b>Discrepancy Detection</b>") {
            input "discrepancyThresholdPct", "decimal",
                title: "Alert when import or export kWh differ between sources by more than (%) — set 0 to disable",
                defaultValue: 5.0, range: "0..100", required: false
        }

        section("<b>Billing Period Controls</b>") {
            input "refreshBtn", "button", title: "🔃 Refresh Display"
            input "resetBtn",   "button", title: "🔄 Reset Billing Period Now"
            paragraph "Refresh updates the status below. Reset zeroes all counters and baselines."
            paragraph billingStatusParagraph()
        }

        section("<b>Logging</b>") {
            input "debugLog", "bool", title: "Enable debug logging", defaultValue: false
        }
    }
}

def sourceAPage() {
    dynamicPage(name: "sourceAPage", title: "Source A — PowerMeter / watts", nextPage: "mainPage") {

        section("<b>Source A devices (Emporia Vue or any PowerMeter)</b>") {
            paragraph """Devices exposing a <i>power</i> attribute in watts. Leave both blank 
to disable Source A entirely. Watts are integrated every minute to kWh internally. 
The grid import device also feeds the 15-minute demand buffer — when Source A is 
active its peak demand is used for both sources' billing calculations."""

            input "gridImportDevice", "capability.powerMeter",
                title: "Mains FROM grid — watts consumed from the utility",
                description: "e.g. Emporia 'mains from grid' CT channel",
                required: false, multiple: false

            input "solarExportDevice", "capability.powerMeter",
                title: "Mains TO grid — watts your solar sends to the grid",
                description: "e.g. Emporia 'mains to grid' CT channel",
                required: false, multiple: false
        }

        section("<b>How Source A works</b>") {
            paragraph """Every minute the app reads watts from both devices. Each reading 
is converted to a kWh increment (watts ÷ 1000 ÷ 60) and added to running 
totals. Negative readings are treated as zero. The import device's readings 
are also added to a 15-sample rolling buffer; when full, the 15-minute 
average kW is compared to the stored peak for the billing period."""
        }
    }
}

def sourceBPage() {
    dynamicPage(name: "sourceBPage", title: "Source B — EnergyMeter / kWh", nextPage: "mainPage") {

        section("<b>Source B devices (Aeotec or any never-resetting EnergyMeter)</b>") {
            paragraph """Devices exposing an <i>energy</i> attribute in kWh that increases 
monotonically and never resets. The app snapshots both values at billing 
period start and computes usage as <b>current − baseline</b> each minute. 
Leave both blank to disable Source B entirely."""

            input "gridKwhDevice", "capability.energyMeter",
                title: "Grid consumption — total kWh drawn from NB Power (never resets)",
                description: "e.g. Aeotec mains import channel",
                required: false, multiple: false

            input "solarKwhDevice", "capability.energyMeter",
                title: "Solar production — total kWh generated by inverter (never resets)",
                description: "e.g. Aeotec reading from your inverter's total production counter",
                required: false, multiple: false
        }

        section("<b>Peak demand for Source B</b>") {
            paragraph """If Source A (watts) is also active, its peak demand figure is 
automatically used here — no extra device needed. If Source A is disabled, 
you can optionally select a PowerMeter below; otherwise peak demand is 
estimated from the per-minute kWh delta (less precise but functional)."""

            input "peakWattsDevice", "capability.powerMeter",
                title: "Optional: dedicated PowerMeter for peak demand (watts)",
                description: "Only needed if Source A devices are not configured",
                required: false, multiple: false
        }

        section("<b>How Source B works</b>") {
            paragraph """At billing period start both kWh counters are snapshotted. Every 
minute the app reads both current values and subtracts the baselines to 
get period totals. Because these counters never reset, hub reboots do not 
affect accuracy. The solar device should report total inverter production 
(all kWh generated, whether self-consumed or exported)."""
        }
    }
}

def ratesPage() {
    dynamicPage(name: "ratesPage", title: "Rate Settings", nextPage: "mainPage") {

        section("<b>Current NB Power Net Metering Rate</b>") {
            paragraph "Under the current programme, import and export offset at the same rate (1:1)."
            input "currentNetRate", "decimal",
                title: "Net metering rate (¢/kWh)",
                defaultValue: 14.76, range: "0.01..99.99", required: true
        }

        section("<b>Proposed Rate Structure</b>") {
            paragraph "Pending EUB approval for April 1, 2027. Adjust as NB Power confirms final numbers."
            input "proposedImportRate", "decimal",
                title: "Import rate — energy drawn from grid (¢/kWh)",
                defaultValue: 14.76, range: "0.01..99.99", required: true
            input "proposedExportRate", "decimal",
                title: "Export credit — energy sent to grid (¢/kWh)",
                defaultValue: 6.77, range: "0.01..99.99", required: true
            input "demandChargeRate", "decimal",
                title: "Demand charge rate (\$/kW of peak 15-min demand)",
                defaultValue: 13.00, range: "0.01..99.99", required: true
        }

        section("<b>Demand charge window</b>") {
            paragraph "NB Power's proposal applies the demand charge only between <b>7:00 am and 10:00 pm</b>."
            input "demandWindowStart", "number",
                title: "Window start hour (0–23, default 7)",
                defaultValue: 7, range: "0..23", required: true
            input "demandWindowEnd", "number",
                title: "Window end hour (0–23, default 22 = 10:00 pm)",
                defaultValue: 22, range: "0..23", required: true
        }
    }
}

def notificationsPage() {
    dynamicPage(name: "notificationsPage", title: "Notifications", nextPage: "mainPage") {
        section("<b>Demand spike alert</b>") {
            paragraph "Sends a notification when instantaneous grid draw exceeds a threshold."
            input "notifyDevices", "capability.notification",
                title: "Notification devices", required: false, multiple: true
            input "spikeThresholdKw", "decimal",
                title: "Alert when grid draw exceeds (kW) — set 0 to disable",
                defaultValue: 0, range: "0..100", required: false
            input "spikeAlertCooldownMin", "number",
                title: "Minimum minutes between spike alerts",
                defaultValue: 30, range: "1..1440", required: false
        }
        section("<b>Discrepancy alert</b>") {
            paragraph "Sends a notification when Source A and Source B readings diverge " +
                      "beyond the threshold set on the main page. Uses the same notification devices."
            input "discrepancyAlertCooldownMin", "number",
                title: "Minimum minutes between discrepancy alerts",
                defaultValue: 60, range: "1..1440", required: false
        }
        section("<b>Monthly summary notification</b>") {
            input "sendMonthlySummary", "bool",
                title: "Send billing summary at start of each new period",
                defaultValue: true
        }
    }
}

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------
def installed() {
    logDebug "Installed"
    initialize()
}

def updated() {
    logDebug "Updated — re-initialising"
    unsubscribe()
    unschedule()
    initialize()
}

def initialize() {
    if (state.billingStart == null) resetBillingPeriod()
    schedule("0 * * * * ?", "everyMinute")
    schedule("0 0 0 ${billingDay} * ?", "autoBillingReset")

    def active = []
    if (sourceAActive()) active << "Source A (watts)"
    if (sourceBActive()) active << "Source B (kWh)"
    logInfo "Initialised. Active sources: ${active ?: ['none — configure devices']}. " +
            "Billing period: ${currentBillingPeriodLabel()}"
    refreshSummary()
}

// ---------------------------------------------------------------------------
// Source availability helpers
// ---------------------------------------------------------------------------
boolean sourceAActive() { return gridImportDevice && solarExportDevice }
boolean sourceBActive() { return gridKwhDevice && solarKwhDevice }

// ---------------------------------------------------------------------------
// Button handler
// ---------------------------------------------------------------------------
def appButtonHandler(btn) {
    if (btn == "refreshBtn") {
        logDebug "Manual display refresh."
        refreshSummary()
    } else if (btn == "resetBtn") {
        logInfo "Manual billing period reset."
        endOfPeriodSummary()
        resetBillingPeriod()
        refreshSummary()
    }
}

// ---------------------------------------------------------------------------
// Billing period reset
// ---------------------------------------------------------------------------
def autoBillingReset() {
    logInfo "Automatic billing period reset on day ${billingDay}."
    if (sendMonthlySummary) endOfPeriodSummary()
    resetBillingPeriod()
    refreshSummary()
}

def resetBillingPeriod() {
    def ts = now()
    state.billingStart    = ts
    state.billingStartStr = formatDate(ts)

    // Source A — watt integration totals
    state.aImportKwh = 0.0
    state.aExportKwh = 0.0

    // Source B — never-resetting kWh baselines
    state.bImportBase = safeEnergy(gridKwhDevice)
    state.bExportBase = safeEnergy(solarKwhDevice)

    // Peak demand (shared — Source A watts is preferred source)
    state.minuteWatts      = []
    state.peakKw           = 0.0
    state.peakKwTime       = ""

    // Alert cooldowns
    state.lastSpikeAlert       = 0L
    state.lastDiscrepancyAlert = 0L

    logInfo "Billing period reset at ${state.billingStartStr}." +
            (sourceBActive() ? " Source B baselines — Grid: ${state.bImportBase} kWh, Solar: ${state.bExportBase} kWh." : "")
}

// ---------------------------------------------------------------------------
// Every-minute handler
// ---------------------------------------------------------------------------
def everyMinute() {
    // ── Source A: integrate watts to kWh ────────────────────────────────
    double importW = 0.0
    if (sourceAActive()) {
        importW              = Math.max(0.0, safeWatts(gridImportDevice))
        double exportW       = Math.max(0.0, safeWatts(solarExportDevice))
        state.aImportKwh     = (state.aImportKwh ?: 0.0) + (importW / 1000.0 / 60.0)
        state.aExportKwh     = (state.aExportKwh ?: 0.0) + (exportW / 1000.0 / 60.0)
    }

    // ── Peak demand ──────────────────────────────────────────────────────
    // Priority: Source A import watts → dedicated peakWattsDevice → Source B kWh delta
    double wattsForDemand = 0.0
    if (sourceAActive()) {
        wattsForDemand = importW
    } else if (peakWattsDevice) {
        wattsForDemand = Math.max(0.0, safeWatts(peakWattsDevice))
    } else if (sourceBActive()) {
        // Estimate from Source B kWh delta
        double prev         = (state.prevBImportKwh ?: safeEnergy(gridKwhDevice)) as double
        double cur          = safeEnergy(gridKwhDevice)
        wattsForDemand      = Math.max(0.0, cur - prev) * 60.0 * 1000.0
        state.prevBImportKwh = cur
    }
    trackDemand(wattsForDemand)

    // ── Spike alert ──────────────────────────────────────────────────────
    checkSpikeAlert(wattsForDemand)

    // ── Discrepancy check ────────────────────────────────────────────────
    if (sourceAActive() && sourceBActive()) checkDiscrepancy()

    refreshSummary()
}

// ---------------------------------------------------------------------------
// Peak demand tracking (shared)
// ---------------------------------------------------------------------------
void trackDemand(double wattsNow) {
    int hr       = Calendar.getInstance(location.timeZone).get(Calendar.HOUR_OF_DAY)
    int winStart = (demandWindowStart ?: 7) as int
    int winEnd   = (demandWindowEnd   ?: 22) as int

    if (hr >= winStart && hr < winEnd) {
        List buf = state.minuteWatts ?: []
        buf << wattsNow
        if (buf.size() > 15) buf = buf.drop(buf.size() - 15)
        state.minuteWatts = buf

        if (buf.size() == 15) {
            double avgKw = (buf.sum() / 15.0) / 1000.0
            if (avgKw > (state.peakKw ?: 0.0)) {
                state.peakKw     = avgKw.round(4)
                state.peakKwTime = formatDate(now())
                logDebug "New peak 15-min demand: ${state.peakKw} kW at ${state.peakKwTime}"
            }
        }
    } else {
        state.minuteWatts = []
    }
}

// ---------------------------------------------------------------------------
// Spike alert
// ---------------------------------------------------------------------------
void checkSpikeAlert(double wattsNow) {
    double threshKw = (spikeThresholdKw ?: 0) as double
    if (threshKw <= 0) return
    if ((wattsNow / 1000.0) <= threshKw) return
    long cooldownMs = ((spikeAlertCooldownMin ?: 30) * 60 * 1000) as long
    if ((now() - (state.lastSpikeAlert ?: 0L)) > cooldownMs) {
        state.lastSpikeAlert = now()
        double kw     = (wattsNow / 1000.0).round(2)
        double impact = (kw * (demandChargeRate ?: 13.0)).round(2)
        sendNotifications(
            "⚡ Demand spike: grid draw is ${kw} kW (threshold ${threshKw} kW). " +
            "If sustained 15 min, demand charge impact: \$${impact}."
        )
    }
}

// ---------------------------------------------------------------------------
// Discrepancy check
// ---------------------------------------------------------------------------
void checkDiscrepancy() {
    double thresh = (discrepancyThresholdPct ?: 5.0) as double
    if (thresh <= 0) return

    double aImp = aImportKwh()
    double bImp = bImportKwh()
    double aExp = aExportKwh()
    double bExp = bExportKwh()

    // Only compare once each source has accumulated something meaningful (>1 kWh)
    if (aImp < 1.0 || bImp < 1.0) return

    double impDiffPct = Math.abs(aImp - bImp) / Math.max(aImp, bImp) * 100.0
    double expDiffPct = (Math.max(aExp, bExp) > 0.5) ?
                        Math.abs(aExp - bExp) / Math.max(aExp, bExp) * 100.0 : 0.0

    if (impDiffPct > thresh || expDiffPct > thresh) {
        long cooldownMs = ((discrepancyAlertCooldownMin ?: 60) * 60 * 1000) as long
        if ((now() - (state.lastDiscrepancyAlert ?: 0L)) > cooldownMs) {
            state.lastDiscrepancyAlert = now()
            def lines = []
            if (impDiffPct > thresh)
                lines << "Import: A=${aImp.round(2)} kWh vs B=${bImp.round(2)} kWh (${impDiffPct.round(1)}% difference)"
            if (expDiffPct > thresh)
                lines << "Export: A=${aExp.round(2)} kWh vs B=${bExp.round(2)} kWh (${expDiffPct.round(1)}% difference)"
            sendNotifications(
                "⚠️ Meter discrepancy detected:\n" + lines.join("\n") +
                "\nCheck your device configurations and wiring."
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Per-source kWh calculations
// ---------------------------------------------------------------------------
double aImportKwh() { return (state.aImportKwh ?: 0.0) as double }
double aExportKwh() { return (state.aExportKwh ?: 0.0) as double }

double bImportKwh() {
    if (!sourceBActive()) return 0.0
    double cur  = safeEnergy(gridKwhDevice)
    double base = (state.bImportBase ?: 0.0) as double
    return Math.max(0.0, cur - base)
}

double bExportKwh() {
    if (!sourceBActive()) return 0.0
    double cur  = safeEnergy(solarKwhDevice)
    double base = (state.bExportBase ?: 0.0) as double
    return Math.max(0.0, cur - base)
}

double peakKw() { return (state.peakKw ?: 0.0) as double }

// ---------------------------------------------------------------------------
// Per-source billing calculations (peak is shared)
// ---------------------------------------------------------------------------
Map calcCosts(double imp, double exp, double peak) {
    double netKwh       = imp - exp
    double currentCost  = (netKwh   * ((currentNetRate    ?: 14.76) / 100.0)).round(2)
    double importCost   = (imp      * ((proposedImportRate ?: 14.76) / 100.0)).round(2)
    double exportCredit = (exp      * ((proposedExportRate ?: 6.77)  / 100.0)).round(2)
    double demandCost   = (peak     *  (demandChargeRate   ?: 13.00)).round(2)
    double proposedCost = (importCost - exportCredit + demandCost).round(2)
    double delta        = (proposedCost - currentCost).round(2)
    return [
        currentCost:  currentCost,
        importCost:   importCost,
        exportCredit: exportCredit,
        demandCost:   demandCost,
        proposedCost: proposedCost,
        delta:        delta
    ]
}

// ---------------------------------------------------------------------------
// Summary / dashboard
// ---------------------------------------------------------------------------
def refreshSummary() {
    double peak  = peakKw()
    boolean hasA = sourceAActive()
    boolean hasB = sourceBActive()

    double aImp  = aImportKwh().round(2)
    double aExp  = aExportKwh().round(2)
    double bImp  = bImportKwh().round(2)
    double bExp  = bExportKwh().round(2)

    Map aC = hasA ? calcCosts(aImp, aExp, peak) : null
    Map bC = hasB ? calcCosts(bImp, bExp, peak) : null

    logDebug "=== Refresh ===" +
             (hasA ? " | A: imp=${aImp} exp=${aExp} cur=\$${aC.currentCost} prop=\$${aC.proposedCost}" : "") +
             (hasB ? " | B: imp=${bImp} exp=${bExp} cur=\$${bC.currentCost} prop=\$${bC.proposedCost}" : "") +
             " | Peak: ${peak} kW"

    if (summaryDevice) {
        if (hasA) {
            sendEvent(summaryDevice, [name: "nbpA_ImportKwh",    value: aImp,                                  unit: "kWh"])
            sendEvent(summaryDevice, [name: "nbpA_ExportKwh",    value: aExp,                                  unit: "kWh"])
            sendEvent(summaryDevice, [name: "nbpA_PeakKw",       value: peak.round(3),                         unit: "kW"])
            sendEvent(summaryDevice, [name: "nbpA_CurrentCost",  value: aC.currentCost,                        unit: "\$"])
            sendEvent(summaryDevice, [name: "nbpA_ProposedCost", value: aC.proposedCost,                       unit: "\$"])
            sendEvent(summaryDevice, [name: "nbpA_Delta",        value: "${aC.delta >= 0 ? '+' : ''}${aC.delta}", unit: "\$"])
        }
        if (hasB) {
            sendEvent(summaryDevice, [name: "nbpB_ImportKwh",    value: bImp,                                  unit: "kWh"])
            sendEvent(summaryDevice, [name: "nbpB_ExportKwh",    value: bExp,                                  unit: "kWh"])
            sendEvent(summaryDevice, [name: "nbpB_CurrentCost",  value: bC.currentCost,                        unit: "\$"])
            sendEvent(summaryDevice, [name: "nbpB_ProposedCost", value: bC.proposedCost,                       unit: "\$"])
            sendEvent(summaryDevice, [name: "nbpB_Delta",        value: "${bC.delta >= 0 ? '+' : ''}${bC.delta}", unit: "\$"])
        }
        sendEvent(summaryDevice, [name: "nbpPeakKw",       value: peak.round(3),           unit: "kW"])
        sendEvent(summaryDevice, [name: "nbpPeakKwTime",   value: state.peakKwTime ?: "—"])
        sendEvent(summaryDevice, [name: "nbpBillingStart", value: state.billingStartStr ?: "—"])

        // Discrepancy summary attribute
        if (hasA && hasB) {
            double impDiff = (aImp - bImp).abs().round(2)
            double expDiff = (aExp - bExp).abs().round(2)
            sendEvent(summaryDevice, [name: "nbpDiscrepancy",
                value: "Imp Δ: ${impDiff} kWh | Exp Δ: ${expDiff} kWh"])
        }
    }
}

// ---------------------------------------------------------------------------
// End-of-period summary notification
// ---------------------------------------------------------------------------
def endOfPeriodSummary() {
    double peak  = peakKw()
    boolean hasA = sourceAActive()
    boolean hasB = sourceBActive()

    double aImp  = aImportKwh().round(2)
    double aExp  = aExportKwh().round(2)
    double bImp  = bImportKwh().round(2)
    double bExp  = bExportKwh().round(2)

    Map aC = hasA ? calcCosts(aImp, aExp, peak) : null
    Map bC = hasB ? calcCosts(bImp, bExp, peak) : null

    def sb = new StringBuilder()
    sb << "📊 NB Power Billing Period Summary\n"
    sb << "Period : ${state.billingStartStr} – ${formatDate(now())}\n"
    sb << "Peak 15-min demand: ${peak.round(3)} kW  (at ${state.peakKwTime ?: 'not recorded'})\n"
    sb << "─────────────────────────────────────\n"

    if (hasA) {
        sb << "SOURCE A (Emporia / watts)\n"
        sb << "  Grid import  : ${aImp} kWh\n"
        sb << "  Solar export : ${aExp} kWh\n"
        sb << "  Net kWh      : ${(aImp - aExp).round(2)} kWh\n"
        sb << "  Current net metering  : \$${aC.currentCost}\n"
        sb << "  Proposed structure    : \$${aC.proposedCost}\n"
        sb << "    Import  ${aImp} kWh × ${proposedImportRate}¢  =  \$${aC.importCost}\n"
        sb << "    Export  ${aExp} kWh × ${proposedExportRate}¢  = −\$${aC.exportCredit}\n"
        sb << "    Demand  ${peak.round(3)} kW × \$${demandChargeRate}  =  \$${aC.demandCost}\n"
        sb << "  Proposed vs. current  : ${aC.delta >= 0 ? '+' : ''}\$${aC.delta}\n"
        sb << "  Annualised projection : ${aC.delta >= 0 ? '+' : ''}\$${(aC.delta * 12).round(0)}/yr\n"
        sb << "─────────────────────────────────────\n"
    }

    if (hasB) {
        sb << "SOURCE B (Aeotec / kWh)\n"
        sb << "  Grid import       : ${bImp} kWh\n"
        sb << "  Solar production  : ${bExp} kWh\n"
        sb << "  Net kWh           : ${(bImp - bExp).round(2)} kWh\n"
        sb << "  Current net metering  : \$${bC.currentCost}\n"
        sb << "  Proposed structure    : \$${bC.proposedCost}\n"
        sb << "    Import  ${bImp} kWh × ${proposedImportRate}¢  =  \$${bC.importCost}\n"
        sb << "    Export  ${bExp} kWh × ${proposedExportRate}¢  = −\$${bC.exportCredit}\n"
        sb << "    Demand  ${peak.round(3)} kW × \$${demandChargeRate}  =  \$${bC.demandCost}\n"
        sb << "  Proposed vs. current  : ${bC.delta >= 0 ? '+' : ''}\$${bC.delta}\n"
        sb << "  Annualised projection : ${bC.delta >= 0 ? '+' : ''}\$${(bC.delta * 12).round(0)}/yr\n"
        sb << "─────────────────────────────────────\n"
    }

    if (hasA && hasB) {
        double impDiffPct = (Math.max(aImp, bImp) > 0) ?
            ((aImp - bImp).abs() / Math.max(aImp, bImp) * 100.0).round(1) : 0.0
        double expDiffPct = (Math.max(aExp, bExp) > 0) ?
            ((aExp - bExp).abs() / Math.max(aExp, bExp) * 100.0).round(1) : 0.0
        sb << "CROSS-SOURCE COMPARISON\n"
        sb << "  Import difference  : ${(aImp - bImp).round(2)} kWh (${impDiffPct}%)\n"
        sb << "  Export difference  : ${(aExp - bExp).round(2)} kWh (${expDiffPct}%)\n"
        sb << "  Cost delta (A−B)   : \$${(aC.proposedCost - bC.proposedCost).round(2)} proposed\n"
    }

    def msg = sb.toString()
    logInfo msg
    sendNotifications(msg)
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------
double safeWatts(dev) {
    try {
        def v = dev?.currentValue("power")
        return (v != null) ? (v as double) : 0.0
    } catch (e) { logDebug "safeWatts error: ${e.message}"; return 0.0 }
}

double safeEnergy(dev) {
    try {
        def v = dev?.currentValue("energy")
        return (v != null) ? (v as double) : 0.0
    } catch (e) { logDebug "safeEnergy error: ${e.message}"; return 0.0 }
}

void sendNotifications(String msg) { notifyDevices?.each { it.deviceNotification(msg) } }

String formatDate(long ts) { return new Date(ts).format("yyyy-MM-dd HH:mm", location.timeZone) }

String currentBillingPeriodLabel() {
    def now = new Date()
    int day = now.date; int yr = now.year + 1900; int mo = now.month
    int bd  = (billingDay ?: 1) as int
    Date start
    if (day >= bd) {
        start = Date.parse("yyyy-M-d", "${yr}-${mo + 1}-${bd}")
    } else {
        def cal = Calendar.getInstance(); cal.set(yr, mo - 1, bd); start = cal.time
    }
    return start.format("MMM d") + " – " + (start + 30).format("MMM d, yyyy")
}

// ---------------------------------------------------------------------------
// Status paragraph shown on main page
// ---------------------------------------------------------------------------
String billingStatusParagraph() {
    double peak  = peakKw()
    boolean hasA = sourceAActive()
    boolean hasB = sourceBActive()

    if (!hasA && !hasB) return "<b>No sources configured.</b> Set up at least one source in the Meter Sources section above."

    double aImp  = aImportKwh().round(2)
    double aExp  = aExportKwh().round(2)
    double bImp  = bImportKwh().round(2)
    double bExp  = bExportKwh().round(2)
    Map aC = hasA ? calcCosts(aImp, aExp, peak) : null
    Map bC = hasB ? calcCosts(bImp, bExp, peak) : null

    def sb = new StringBuilder()
    sb << "<b>Period started:</b> ${state.billingStartStr ?: '(not set)'}<br>"
    sb << "<b>Peak 15-min demand:</b> ${peak.round(3)} kW (at ${state.peakKwTime ?: '—'})<br>"

    if (hasA) {
        String aSign = aC.delta >= 0 ? "+" : ""
        sb << "<br><b>── Source A (Emporia / watts) ──</b><br>"
        sb << "Import: <b>${aImp} kWh</b> &nbsp; Export: <b>${aExp} kWh</b><br>"
        sb << "Current net metering: <b>\$${aC.currentCost}</b><br>"
        sb << "Proposed structure:   <b>\$${aC.proposedCost}</b>"
        sb << " &nbsp; Δ <b>${aSign}\$${aC.delta}</b><br>"
    }

    if (hasB) {
        String bSign = bC.delta >= 0 ? "+" : ""
        sb << "<br><b>── Source B (Aeotec / kWh) ──</b><br>"
        sb << "Import: <b>${bImp} kWh</b> &nbsp; Solar production: <b>${bExp} kWh</b><br>"
        sb << "Current net metering: <b>\$${bC.currentCost}</b><br>"
        sb << "Proposed structure:   <b>\$${bC.proposedCost}</b>"
        sb << " &nbsp; Δ <b>${bSign}\$${bC.delta}</b><br>"
    }

    if (hasA && hasB) {
        double impDiff    = (aImp - bImp).round(2)
        double expDiff    = (aExp - bExp).round(2)
        double impDiffPct = (Math.max(aImp, bImp) > 0) ?
            ((aImp - bImp).abs() / Math.max(aImp, bImp) * 100.0).round(1) : 0.0
        double expDiffPct = (Math.max(aExp, bExp) > 0) ?
            ((aExp - bExp).abs() / Math.max(aExp, bExp) * 100.0).round(1) : 0.0
        double thresh     = (discrepancyThresholdPct ?: 5.0) as double

        String impFlag = impDiffPct > thresh ? " ⚠️" : " ✅"
        String expFlag = expDiffPct > thresh ? " ⚠️" : " ✅"

        sb << "<br><b>── Cross-source comparison ──</b><br>"
        sb << "Import diff: <b>${impDiff >= 0 ? '+' : ''}${impDiff} kWh (${impDiffPct}%)</b>${impFlag}<br>"
        sb << "Export diff: <b>${expDiff >= 0 ? '+' : ''}${expDiff} kWh (${expDiffPct}%)</b>${expFlag}<br>"
        sb << "Proposed cost diff (A−B): <b>\$${(aC.proposedCost - bC.proposedCost).round(2)}</b>"
    }

    return sb.toString()
}

// ---------------------------------------------------------------------------
// Devices page description strings
// ---------------------------------------------------------------------------
String sourceADescription() {
    if (!gridImportDevice && !solarExportDevice) return "Not configured (optional)"
    if (!gridImportDevice || !solarExportDevice) return "⚠️ Partially configured — both devices required"
    return "From grid: ${gridImportDevice.displayName}\nTo grid:   ${solarExportDevice.displayName}"
}

String sourceBDescription() {
    if (!gridKwhDevice && !solarKwhDevice) return "Not configured (optional)"
    if (!gridKwhDevice || !solarKwhDevice) return "⚠️ Partially configured — both devices required"
    return "Grid: ${gridKwhDevice.displayName}\nSolar: ${solarKwhDevice.displayName}" +
           (peakWattsDevice ? "\nPeak meter: ${peakWattsDevice.displayName}" : "")
}

String ratesDescription() {
    return "Net: ${currentNetRate}¢ | Import: ${proposedImportRate}¢ | " +
           "Export: ${proposedExportRate}¢ | Demand: \$${demandChargeRate}/kW"
}

String notifyDescription() {
    if (!notifyDevices) return "No notifications configured"
    return "${notifyDevices.size()} device(s) | Spike: ${spikeThresholdKw ?: 'off'} kW | " +
           "Discrepancy: ${discrepancyThresholdPct ?: 5}%"
}

void logDebug(msg) { if (debugLog) log.debug "[NBPSolar] ${msg}" }
void logInfo(msg)  { log.info  "[NBPSolar] ${msg}" }
